version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.0
workflows:
  build:
    jobs:
      - cypress/install:
           build: "npm install"
      - cypress/run:
           record: true
           parallel: true
           parallelism: 2