# # to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.7.0
# workflows:
#   build:
#     jobs:
#       # install dependencies first
#       - cypress/install
#       # now run tests
#       - cypress/run:
#           # give this job a custom name for clarity
#           name: 'end-to-end tests'
#           requires:
#             # use previously installed dependencies
#             # to avoid installing them on each machine running tests
#             - cypress/install
#           record: true # record results to Cypress Dashboard
#           parallel: true # run tests in parallel
#           parallelism: 3 # use 3 CircleCI machines
#           group: 3 machines # name this group "3 machines"

version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:10
    record: true
    parallel: true
    parallelism: 3
    group: 3 machines
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Npm CI
        command: npm ci
    - run:
        command: npx cypress verify
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - attach_workspace:
        at: ~/
    - run:
        name: Run Cypress tests
        command: 'npx percy exec -- cypress run'
workflows:
  build:
    jobs:
    - cypress/run
  version: 2